In [1]:
import pandas as pd
fun=pd.read_csv("funcionarios_datas.csv")
display(fun)

fun["Data"]=pd.to_datetime(fun["Data"],dayfirst=True)
display(fun["Data"].dtype)

    ID     Nome        Data Departamento
0    1   Amanda  05/01/2026           TI
1    2     João  12/01/2026           RH
2    3    Maria  20/01/2026       Vendas
3    4    Pedro  03/02/2026           TI
4    5      Ana  15/02/2026   Financeiro
5    6    Lucas  28/02/2026           RH
6    7    Carla  07/03/2026           TI
7    8   Rafael  18/03/2026       Vendas
8    9  Juliana  25/03/2026   Financeiro
9   10    Bruno  02/04/2026           TI
10  11   Camila  10/04/2026           RH
11  12   Felipe  22/04/2026       Vendas
12  13  Larissa  05/05/2026           TI
13  14  Gustavo  16/05/2026   Financeiro
14  15  Beatriz  29/05/2026           RH
15  16   Daniel  08/06/2026       Vendas
16  17  Mariana  19/06/2026           TI
17  18   Thiago  01/07/2026           RH
18  19  Isabela  14/07/2026   Financeiro
19  20  Gabriel  25/07/2026           TI

dtype('<M8[us]')

In [2]:
#5. Crie uma coluna chamada Ano contendo somente o ano da Data.
fun["Ano"]=fun["Data"].dt.year
display(fun)

    ID     Nome       Data Departamento   Ano
0    1   Amanda 2026-01-05           TI  2026
1    2     João 2026-01-12           RH  2026
2    3    Maria 2026-01-20       Vendas  2026
3    4    Pedro 2026-02-03           TI  2026
4    5      Ana 2026-02-15   Financeiro  2026
5    6    Lucas 2026-02-28           RH  2026
6    7    Carla 2026-03-07           TI  2026
7    8   Rafael 2026-03-18       Vendas  2026
8    9  Juliana 2026-03-25   Financeiro  2026
9   10    Bruno 2026-04-02           TI  2026
10  11   Camila 2026-04-10           RH  2026
11  12   Felipe 2026-04-22       Vendas  2026
12  13  Larissa 2026-05-05           TI  2026
13  14  Gustavo 2026-05-16   Financeiro  2026
14  15  Beatriz 2026-05-29           RH  2026
15  16   Daniel 2026-06-08       Vendas  2026
16  17  Mariana 2026-06-19           TI  2026
17  18   Thiago 2026-07-01           RH  2026
18  19  Isabela 2026-07-14   Financeiro  2026
19  20  Gabriel 2026-07-25           TI  2026

In [ ]:
#6. Crie uma coluna chamada Mes contendo o número do mês.
fun["Mês"]=fun["Data"].dt.month
display(fun)

In [ ]:
#7. Crie uma coluna chamada Dia contendo o dia.
fun["Dia"]=fun["Data"].dt.day
display(fun)

In [7]:
#8. Crie uma coluna chamada Dia_Semana contendo o nome do dia da semana.
fun["Dia da Semana"]=fun["Data"].dt.day_name()
display(fun)

    ID     Nome       Data Departamento Dia da Semana
0    1   Amanda 2026-01-05           TI        Monday
1    2     João 2026-01-12           RH        Monday
2    3    Maria 2026-01-20       Vendas       Tuesday
3    4    Pedro 2026-02-03           TI       Tuesday
4    5      Ana 2026-02-15   Financeiro        Sunday
5    6    Lucas 2026-02-28           RH      Saturday
6    7    Carla 2026-03-07           TI      Saturday
7    8   Rafael 2026-03-18       Vendas     Wednesday
8    9  Juliana 2026-03-25   Financeiro     Wednesday
9   10    Bruno 2026-04-02           TI      Thursday
10  11   Camila 2026-04-10           RH        Friday
11  12   Felipe 2026-04-22       Vendas     Wednesday
12  13  Larissa 2026-05-05           TI       Tuesday
13  14  Gustavo 2026-05-16   Financeiro      Saturday
14  15  Beatriz 2026-05-29           RH        Friday
15  16   Daniel 2026-06-08       Vendas        Monday
16  17  Mariana 2026-06-19           TI        Friday
17  18   Thiago 2026-07-01           RH     Wednesday
18  19  Isabela 2026-07-14   Financeiro       Tuesday
19  20  Gabriel 2026-07-25           TI      Saturday

In [ ]:
janeiro=fun[fun["Data"].dt.month==1]
display(fun)

In [ ]:
#10. Mostre somente os funcionários registrados no mês de maio.
maio=fun[fun["Data"].dt.month==5]
display(maio)

In [4]:
#11. Mostre somente os funcionários registrados no ano de 2026.
ano_2026=fun[fun["Data"].dt.year==2026]
display(ano_2026)

    ID     Nome       Data Departamento
0    1   Amanda 2026-01-05           TI
1    2     João 2026-01-12           RH
2    3    Maria 2026-01-20       Vendas
3    4    Pedro 2026-02-03           TI
4    5      Ana 2026-02-15   Financeiro
5    6    Lucas 2026-02-28           RH
6    7    Carla 2026-03-07           TI
7    8   Rafael 2026-03-18       Vendas
8    9  Juliana 2026-03-25   Financeiro
9   10    Bruno 2026-04-02           TI
10  11   Camila 2026-04-10           RH
11  12   Felipe 2026-04-22       Vendas
12  13  Larissa 2026-05-05           TI
13  14  Gustavo 2026-05-16   Financeiro
14  15  Beatriz 2026-05-29           RH
15  16   Daniel 2026-06-08       Vendas
16  17  Mariana 2026-06-19           TI
17  18   Thiago 2026-07-01           RH
18  19  Isabela 2026-07-14   Financeiro
19  20  Gabriel 2026-07-25           TI

In [8]:
#12. Mostre somente os registros que aconteceram em uma segunda-feira.
segunda=fun[fun["Data"].dt.day_name()=="Monday"]
display(segunda)

    ID    Nome       Data Departamento Dia da Semana
0    1  Amanda 2026-01-05           TI        Monday
1    2    João 2026-01-12           RH        Monday
15  16  Daniel 2026-06-08       Vendas        Monday

In [ ]:
#13. Conte quantos funcionários foram registrados em cada mês.
cont_fun=fun["Data"].dt.month.value_counts()
display(cont_fun)

Data
1    3
2    3
3    3
4    3
5    3
7    3
6    2
Name: count, dtype: int64

In [ ]:
#14. Conte quantos funcionários foram registrados em cada dia da semana.
cont_fun=fun["Data"].dt.day_of_week.value_counts()
display(cont_fun)

In [4]:
#15. Conte quantos funcionários foram registrados em cada departamento por mês.
fun["Mes"]=fun["Data"].dt.month
cont_fun=fun.groupby(["Departamento","Mes"]).size()
display(cont_fun)

Departamento  Mes
Financeiro    2      1
              3      1
              5      1
              7      1
RH            1      1
              2      1
              4      1
              5      1
              7      1
TI            1      1
              2      1
              3      1
              4      1
              5      1
              6      1
              7      1
Vendas        1      1
              3      1
              4      1
              6      1
dtype: int64

In [11]:
#17. Descubra qual mês teve mais registros.
#18. Descubra qual foi a data mais antiga da tabela.
#19. Descubra qual foi a data mais recente.
#20. Ordene os funcionários da data mais antiga para a mais recente.

fun["Mes_ano"]=fun["Data"].dt.strftime("%m/%Y")
resultado=fun["Mes_ano"].value_counts().idxmax()
display(resultado)

display(fun["Mes_ano"].min())

display(fun["Mes_ano"].max())


display(fun.sort_values(by="Mes_ano", ascending=True))

'01/2026'

'01/2026'

'07/2026'

    ID     Nome       Data Departamento  Mes_ano
0    1   Amanda 2026-01-05           TI  01/2026
1    2     João 2026-01-12           RH  01/2026
2    3    Maria 2026-01-20       Vendas  01/2026
3    4    Pedro 2026-02-03           TI  02/2026
4    5      Ana 2026-02-15   Financeiro  02/2026
5    6    Lucas 2026-02-28           RH  02/2026
6    7    Carla 2026-03-07           TI  03/2026
7    8   Rafael 2026-03-18       Vendas  03/2026
8    9  Juliana 2026-03-25   Financeiro  03/2026
11  12   Felipe 2026-04-22       Vendas  04/2026
9   10    Bruno 2026-04-02           TI  04/2026
10  11   Camila 2026-04-10           RH  04/2026
12  13  Larissa 2026-05-05           TI  05/2026
13  14  Gustavo 2026-05-16   Financeiro  05/2026
14  15  Beatriz 2026-05-29           RH  05/2026
15  16   Daniel 2026-06-08       Vendas  06/2026
16  17  Mariana 2026-06-19           TI  06/2026
18  19  Isabela 2026-07-14   Financeiro  07/2026
17  18   Thiago 2026-07-01           RH  07/2026
19  20  Gabriel 2026-07-25           TI  07/2026