In [2]:
import pandas as pd
import numpy as np

df=pd.read_csv("funcionarios.csv")
display(df)

    ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479

In [ ]:
#Exercício 1
# Mostre apenas os funcionários que têm idade acima da média.

media_idade=df["Idade"].mean()
analise_funcionarios=df[df["Idade"]>media_idade]
display(analise_funcionarios)

    ID      Nome  Idade          Cidade Departamento  Salario
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
6    7    Carlos     42        Brasília       Vendas     4928
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847

In [7]:
#Exercício 2
# Mostre os funcionários que ganham entre 3500 e 5000.
analise_funcionarios=df[(df["Salario"]>=3500) &(df["Salario"]<=5000)]
display(analise_funcionarios)

    ID     Nome  Idade          Cidade Departamento  Salario
0    1   Rafael     21  Rio de Janeiro   Financeiro     4695
4    5    Julia     36       São Paulo           RH     4621
5    6  Beatriz     25         Goiânia   Financeiro     4440
6    7   Carlos     42        Brasília       Vendas     4928
11  12   Rafael     35       São Paulo       Vendas     4522
16  17  Gabriel     44  Belo Horizonte   Financeiro     4847
19  20    Julia     23  Rio de Janeiro           TI     4479

In [ ]:
#Exercício 3
# Mostre os funcionários que trabalham em TI ou RH.
analise_funcionarios=df[(df["Departamento"]=="TI") | (df["Departamento"]=="RH")]
display(analise_funcionarios)

In [ ]:
#Exercício 4
# Mostre apenas os funcionários cuja cidade não é Brasília.
analise_funcionarios=df[df["Cidade"]!="Brasília"]
display(analise_funcionarios)

In [ ]:
#Exercício 5
#Mostre apenas as colunas:Nome, Cidade, dos funcionários com salário acima de 4500.

analise_funcionarios=df[df["Salario"]>4500] [["Nome","Cidade"]]
display(analise_funcionarios)

In [ ]:
#Exercício 6
#Crie uma coluna chamada Bonus.
#O bônus será 10% do salário.
df["Bonus"]=df["Salario"]*0.1
display(df)

In [ ]:
#Exercício 7
#Crie uma coluna chamada Salario_Final.
df["Salario_Final"]=df["Salario"]+df["Bonus"]
display(df)

In [43]:
#Exercício 8
#Mostre apenas os 5 maiores salários.
analise_salario=df.sort_values(by="Salario",ascending=False)
display(analise_salario.head(5))

,ID,Nome,Idade,Cidade,Departamento,Salario,Bonus,Salario_Final
3,4,Fernanda,36,Rio de Janeiro,Financeiro,6201,620.1,6821.1
10,11,Julia,38,Goiânia,Financeiro,6182,618.2,6800.2
1,2,Julia,33,Belo Horizonte,TI,6149,614.9,6763.9
15,16,Larissa,32,São Paulo,Financeiro,5979,597.9,6576.9
18,19,Carlos,22,Brasília,Financeiro,5653,565.3,6218.3

In [45]:
#Exercício 9
#Mostre apenas os 5 menores salários.
analise_salario=df.nsmallest(5,"Salario")
display(analise_salario)

,ID,Nome,Idade,Cidade,Departamento,Salario,Bonus,Salario_Final
13,14,Beatriz,41,Rio de Janeiro,Financeiro,2242,224.2,2466.2
9,10,Julia,38,Rio de Janeiro,RH,2685,268.5,2953.5
14,15,Julia,44,Rio de Janeiro,RH,2756,275.6,3031.6
12,13,Carlos,23,Belo Horizonte,Financeiro,2760,276.0,3036.0
2,3,Beatriz,37,São Paulo,Financeiro,3264,326.4,3590.4

In [9]:
#Exercício 10
#Calcule para cada departamento:
#Média salarial, Maior salário, Menor salário, (Dica: use agg().

analise_salario=df.groupby("Departamento").agg(Media=("Salario","mean"),
                                                           Maior_salario=("Salario","max"),
                                                           Menor_salario=("Salario","min"))
display(analise_funcionarios)

    ID     Nome  Idade          Cidade Departamento  Salario
0    1   Rafael     21  Rio de Janeiro   Financeiro     4695
4    5    Julia     36       São Paulo           RH     4621
5    6  Beatriz     25         Goiânia   Financeiro     4440
6    7   Carlos     42        Brasília       Vendas     4928
11  12   Rafael     35       São Paulo       Vendas     4522
16  17  Gabriel     44  Belo Horizonte   Financeiro     4847
19  20    Julia     23  Rio de Janeiro           TI     4479

In [ ]:
#Exercício 11
#Qual cidade possui a maior média salarial?
media_cidade=df.groupby("Cidade")["Salario"].mean()
analise_cidade=media_cidade.idxmax()
display(analise_cidade)

'Goiânia'

In [64]:
#Exercício 12
# Mostre a soma dos salários de cada departamento.
analise_salario=df.groupby("Departamento") ["Salario"].sum()
display(analise_salario)

Departamento
Financeiro    46263
RH            21176
TI            16239
Vendas         9450
Name: Salario, dtype: int64

In [23]:
#Exercício 13
# Ordene os departamentos pela soma dos salários (maior para menor).
analise_salario=df.groupby("Departamento")["Salario"].sum()
analise_salario=analise_salario.sort_values(ascending=False)
display(analise_salario)

Departamento
Financeiro    46263
RH            21176
TI            16239
Vendas         9450
Name: Salario, dtype: int64

In [ ]:
#Exercício 14
# Mostre os funcionários cujo nome começa com "M".
analise_funcionarios=df[df["Nome"].str.startswith("M")]
display(analise_funcionarios)

In [10]:
#Exercício 15
# Mostre os funcionários cujo nome termina com "a".
analise_funcionarios=df[df["Nome"].str.endswith("a")]
display(analise_funcionarios)

    ID      Nome  Idade          Cidade Departamento  Salario
1    2     Julia     33  Belo Horizonte           TI     6149
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
19  20     Julia     23  Rio de Janeiro           TI     4479

In [ ]:
#Exercício 16
# Mostre todos os funcionários em ordem alfabética.
analise_funcionarios=df.sort_values(by="Nome",ascending=True)
display(analise_funcionarios)

In [ ]:
#Exercício 17
#Mostre os funcionários que possuem idade entre 25 e 35 anos.
analise_funcionarios=df[(df["Idade"]>=25) & (df["Idade"]<=35)]
display(analise_funcionarios)

In [ ]:
#Exercício 18
# Crie uma coluna chamada Faixa_Etaria:
# Até 25 → Jovem
# 26 até 35 → Adulto
# Acima de 35 → Experiente

df["Faixa_Etaria"]=np.where(df["Idade"]<=25,"Jovem", 
np.where(df["Idade"].between(26,35),"Adulto","Experiente"))
display(df)

In [ ]:
#Exercício 19
# Qual departamento possui o maior salário médio?
media_salario=df.groupby("Departamento")["Salario"].mean()
analise_salario=media_salario.idxmax()
display(analise_salario)

'TI'

In [25]:
#Desafio 1 Mostre:
# Cidade
# Quantidade de funcionários
# Média salarial
# Tudo em uma única tabela.

df_analise=df.groupby("Cidade").agg(
    quantidade_funcionarios=("Nome","count"),media_salarial=("Salario","mean")) 
display(df_analise)

                quantidade_funcionarios  media_salarial
Cidade
Belo Horizonte                        5     4974.000000
Brasília                              2     5290.500000
Goiânia                               2     5311.000000
Rio de Janeiro                        7     4095.571429
São Paulo                             4     4596.500000

In [13]:
#Desafio 2 
# Para cada departamento, mostre:
# Quantidade de funcionários
# Média salarial
# Maior salário
# Menor salário
# Soma dos salários
# Tudo usando apenas um groupby().

df_analise=df.groupby("Departamento").agg(QUantidade_Funcionario=("Nome","count"),Media_salario=("Salario","mean"), Maior_Salario=("Salario","max"),
                                         Menor_Salario=("Salario","min"), Soma_Salario=("Salario","sum"))
display(df_analise)

,QUantidade_Funcionario,Media_salario,Maior_Salario,Menor_Salario,Soma_Salario
Departamento,,,,,
Financeiro,10,4626.3,6201,2242,46263
RH,5,4235.2,5634,2685,21176
TI,3,5413.0,6149,4479,16239
Vendas,2,4725.0,4928,4522,9450

In [24]:
#Desafio 3
# Crie um ranking do maior para o menor salário e exiba:
# Nome,Departamento,Salário,Ranking
df["Ranking"]=df["Salario"].rank(ascending=False, method="dense")

df_analise=df[["Nome","Departamento","Salario","Ranking"]]
display(df_analise)

        Nome Departamento  Salario  Ranking
0     Rafael   Financeiro     4695     11.0
1      Julia           TI     6149      3.0
2    Beatriz   Financeiro     3264     16.0
3   Fernanda   Financeiro     6201      1.0
4      Julia           RH     4621     12.0
5    Beatriz   Financeiro     4440     15.0
6     Carlos       Vendas     4928      9.0
7      Julia           TI     5611      7.0
8   Fernanda           RH     5480      8.0
9      Julia           RH     2685     19.0
10     Julia   Financeiro     6182      2.0
11    Rafael       Vendas     4522     13.0
12    Carlos   Financeiro     2760     17.0
13   Beatriz   Financeiro     2242     20.0
14     Julia           RH     2756     18.0
15   Larissa   Financeiro     5979      4.0
16   Gabriel   Financeiro     4847     10.0
17    Rafael           RH     5634      6.0
18    Carlos   Financeiro     5653      5.0
19     Julia           TI     4479     14.0