In [1]:
# Leia o arquivo CSV.

import pandas as pd
import numpy as np

df=pd.read_csv("funcionarios.csv")
display(df)

    ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479

In [ ]:
#Mostre: As 5 primeiras linhas. As 5 últimas linhas.

display(df.head(5))
display(df.tail(5))

In [40]:
# Quantas linhas existem.
# Quantas colunas existem.
# Os tipos de dados de cada coluna.

display(df.shape[0])
display(df.shape[1])
display(df.info)

20

6

<bound method DataFrame.info of     ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479>

In [ ]:
#Mostre apenas as colunas:
#Nome
#Salario
df=df[["Nome","Salario"]]
display(df)

In [ ]:
#Mostre apenas os funcionários que: Ganham mais de 4000.

df_salario=df[df["Salario"]>4000]
display(df_salario)

In [7]:
df_regiao=df[df["Cidade"]=="Brasília"]
display(df_regiao)

    ID    Nome  Idade    Cidade Departamento  Salario
6    7  Carlos     42  Brasília       Vendas     4928
18  19  Carlos     22  Brasília   Financeiro     5653

In [13]:
#Mostre quem: Mora em Goiânia e trabalha em TI.

analise_regiao=df[(df["Cidade"]=="Rio de Janeiro") & (df["Departamento"]=="TI")]
display(analise_regiao)

    ID   Nome  Idade          Cidade Departamento  Salario
7    8  Julia     33  Rio de Janeiro           TI     5611
19  20  Julia     23  Rio de Janeiro           TI     4479

In [ ]:
#Ordene os salários: Do menor para o maior.Do maior para o menor.

maior=df.sort_values(by="Salario", ascending=False)
menor=df.sort_values(by="Salario", ascending=True)
display(maior)
display(menor)

In [ ]:
#Crie uma coluna chamada Salario_Anual.
df["salario_anual"]=df["Salario"]*12
display(df)

In [ ]:
#Crie uma coluna chamada Categoria:
#Salário < 3000 → "Baixo"
#Salário entre 3000 e 5000 → "Médio"
#Salário ≥ 5000 → "Alto"
df["Categorias"]=np.where(
    df["Salario"] <3000, 
    "Baixo", 
np.where(
    (df["Salario"]>= 3000) & (df["Salario"] <5000),
"Médio", "Alto"))
display(df)

In [ ]:
#Descubra:
#Média dos salários.
#Maior salário.
#Menor salário.

df["Média Salário"]=df["Salario"].mean()
df["Maior Salário"]=df["Salario"].max()
df["Menor Salário"]=df["Salario"].min()

display(df)

In [ ]:
#Mostre apenas os funcionários com salário acima da média.
media=df["Salario"].mean()
Fmedia=df[df["Salario"]>media]
display(Fmedia)

In [6]:
#Conte quantos funcionários existem em cada cidade.
fun=df.groupby("Cidade")["Nome"].count()
display(fun)

Cidade
Belo Horizonte    5
Brasília          2
Goiânia           2
Rio de Janeiro    7
São Paulo         4
Name: Nome, dtype: int64

In [ ]:
#Conte quantos funcionários existem em cada departamento.
qtd_fun=df.groupby("Departamento")["Nome"].count()
display(qtd_fun)

In [9]:
#Mostre apenas: Nome, Departamento, Salario dos funcionários que trabalham em Vendas.

df_analise=df[df["Departamento"].isin(["Vendas"])][["Nome","Departamento","Salario"]]
display(df_analise)

      Nome Departamento  Salario
6   Carlos       Vendas     4928
11  Rafael       Vendas     4522

In [ ]:
#Mostre o funcionário com o maior salário.
df_analise=df[df["Salario"]==df["Salario"].max()]["Nome"]
display(df_analise)

In [ ]:
#Mostre os 3 funcionários com os maiores salários.
df_analise=df.nlargest(3,"Salario")["Nome"]
display(df_analise)

In [ ]:
#Calcule a média salarial de cada departamento usando groupby().
media_slr=df.groupby("Departamento")["Salario"].mean()
display(media_slr)