In [ ]:
import pandas as pd
funcionarios=pd.read_csv("funcionarios.csv")
pedidos=pd.read_csv("pedidos.csv")
display(funcionarios,pedidos)

    ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479

    ID_Pedido  ID_Funcionario   Produto   Valor
0         101               1  Notebook  3500.0
1         102               2     Mouse   120.0
2         103               3   Teclado   180.0
3         104               1   Monitor   950.0
4         105               5   Headset   250.0
5         106               7  Notebook  4200.0
6         107               8     Mouse   130.0
7         108              10   Teclado   200.0
8         109              12   Monitor  1100.0
9         110              14    Webcam   300.0
10        111              16  Notebook  3800.0
11        112              17   Headset   280.0
12        113              18     Mouse   150.0
13        114              19   Monitor   980.0
14        115              20   Teclado   210.0

In [ ]:
#1. INNER JOIN
#Faça um merge() entre df_funcionarios e df_pedidos usando a coluna ID.
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="inner"
    
)
display(df_resultado)

Empty DataFrame
Columns: [ID_x, Nome, Idade, Cidade, Departamento, Salario, ID_Pedido, ID_y, Produto, Valor]
Index: []

In [ ]:
#2. LEFT JOIN
#Faça o mesmo, mas usando:
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="left")
display(df_resultado)

In [ ]:
#2. 3. RIGHT JOIN
#Agora use:
#how="right"
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="right")
display(df_resultado)

In [ ]:
#4. OUTER JOIN
#Faça:
#how="outer"
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="outer")
display(df_resultado)

In [ ]:
#5. merge() + seleção
#Faça um merge() inner e mostre somente:
#Nome
#Produto
#Valor
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="inner")
df_resultado=df_resultado[["Nome","Produto","Valor"]]
display(df_resultado)

In [ ]:
#6. merge() + sort_values()
#Faça um merge() inner e mostre os pedidos ordenados pelo maior valor.
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="inner")
df_resultado=df_resultado.sort_values(by="ID_Pedido",ascending=False)
print(df_resultado)

In [23]:
#Exercícios de concat()
#7. Separe os pedidos
#Divida df_pedidos em duas partes:
#Depois junte novamente usando concat().

parte1 = pedidos.iloc[:4]
parte2 = pedidos.iloc[4:]

df_resultado=pd.concat([parte1,parte2])
display(df_resultado)

    ID_Pedido  ID_Funcionario   Produto   Valor
0         101               1  Notebook  3500.0
1         102               2     Mouse   120.0
2         103               3   Teclado   180.0
3         104               1   Monitor   950.0
4         105               5   Headset   250.0
5         106               7  Notebook  4200.0
6         107               8     Mouse   130.0
7         108              10   Teclado   200.0
8         109              12   Monitor  1100.0
9         110              14    Webcam   300.0
10        111              16  Notebook  3800.0
11        112              17   Headset   280.0
12        113              18     Mouse   150.0
13        114              19   Monitor   980.0
14        115              20   Teclado   210.0

In [ ]:
#8. concat() com índice
#Faça novamente usando:
#ignore_index=True
#Observe a diferença no índice.
df_resultado=pd.concat([parte1,parte2],ignore_index=True)
display(df_resultado)

   ID_Pedido  ID_Funcionario   Produto   Valor
0        101               1  Notebook  3500.0
1        102               2     Mouse   120.0
2        103               3   Teclado   180.0
3        104               1   Monitor   950.0
4        105               5   Headset   250.0
5        106               7  Notebook  4200.0
6        107               8     Mouse   130.0
7        108              10   Teclado   200.0

In [ ]:
#Exercícios de join()
#Primeiro prepare os DataFrames:
#9. join()
#Use join() para juntar funcionarios e pedidos.
#Observe o que acontece quando um funcionário possui mais de um pedido.
analise_f = funcionarios[["ID", "Nome"]].set_index("ID")
analise_pe = pedidos[["ID_Funcionario", "Valor"]].set_index("ID_Funcionario")

df_resultado=analise_f.join(analise_pe)
display(df_resultado)

In [ ]:
#10. Desafio 
#Faça um merge() left e descubra:
#Quanto cada funcionário gastou no total.
#O resultado deve ter:
#Nome
#Total gasto

df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                    how="left")
df_resultado=df_resultado.groupby(["ID","Nome"]).agg(Total_gasto=("Valor","sum")).reset_index()
display(df_resultado)

In [ ]:
#No resultado outer, descubra quais registros vieram:
#somente de df_funcionarios
#somente de df_pedidos
#dos dois DataFrames

df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="outer",
                      indicator=True)
display(df_resultado)

In [ ]:
#Exercícios com seleção
#9.Faça um left merge e mostre somente:
#Nome
#Departamento
#Produto
#Valor

df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="left")
df_resultado=df_resultado[["Nome","Departamento","Produto","Valor"]]
display(df_resultado)

In [ ]:
#Faça um inner merge e ordene os resultados pelo maior Valor
df_resultado=pd.merge(funcionarios,
                      pedidos,
                    left_on="ID",
                    right_on="ID_Funcionario",
                    how="inner")
df_resultado=df_resultado.sort_values(by="Valor",ascending=False)
display(df_resultado)

In [20]:
#11.
#Faça um left merge e descubra quantos funcionários não possuem pedidos.
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="left")
df_resultado=df_resultado["ID_Pedido"].isnull().sum()
display(df_resultado)

np.int64(6)

In [ ]:
#Faça um left merge entre funcionários e pedidos.
#Depois:
#Agrupe pelo Nome.
#Calcule o total gasto por cada funcionário.
#Os funcionários sem pedidos devem continuar aparecendo.
df_resultado=pd.merge(funcionarios,
                      pedidos,
                      left_on="ID",
                      right_on="ID_Funcionario",
                      how="left")
df_resultado=df_resultado.groupby("Nome").agg(Total_gasto=("Valor","sum"))
display(df_resultado)