In [3]:
import pandas as pd


dados = {
    "Nome": ["Amanda", "João", "Maria", "Pedro", "Ana"],
    "Idade": [21, 30, 25, 40, 28],
    "Cidade": ["Brasília", "São Paulo", "Rio de Janeiro", "Brasília", "Goiânia"],
    "Salario": [2500, 4200, 3800, 5000, 3100]
}

df = pd.DataFrame(dados)

print(df)

     Nome  Idade          Cidade  Salario
0  Amanda     21        Brasília     2500
1    João     30       São Paulo     4200
2   Maria     25  Rio de Janeiro     3800
3   Pedro     40        Brasília     5000
4     Ana     28         Goiânia     3100

In [89]:
display(df.head(2))
display(df.head(3))

     Nome  Idade     Cidade  Salario  Salario_Anual
0  Amanda     21   Brasília     3000          30000
1    João     30  São Paulo     4200          50400

     Nome  Idade          Cidade  Salario  Salario_Anual
0  Amanda     21        Brasília     3000          30000
1    João     30       São Paulo     4200          50400
2   Maria     25  Rio de Janeiro     3800          45600

In [31]:
display(df[["Nome", "Salario"]])
nova=df.sort_values(by=["Salario"],ascending=True)
display(nova)

     Nome  Salario
0  Amanda     2500
1    João     4200
2   Maria     3800
3   Pedro     5000
4     Ana     3100

     Nome  Idade          Cidade  Salario
0  Amanda     21        Brasília     2500
4     Ana     28         Goiânia     3100
2   Maria     25  Rio de Janeiro     3800
1    João     30       São Paulo     4200
3   Pedro     40        Brasília     5000

In [90]:
display(df.loc[0])
display(df.loc[2])
display(df.loc[1:4])

Nome               Amanda
Idade                  21
Cidade           Brasília
Salario              3000
Salario_Anual       30000
Name: 0, dtype: object

Nome                      Maria
Idade                        25
Cidade           Rio de Janeiro
Salario                    3800
Salario_Anual             45600
Name: 2, dtype: object

    Nome  Idade          Cidade  Salario  Salario_Anual
1   João     30       São Paulo     4200          50400
2  Maria     25  Rio de Janeiro     3800          45600
3  Pedro     40        Brasília     5000          60000
4    Ana     28         Goiânia     3100          37200

In [91]:
salario_maior=df[df["Salario"]>3000]
display(salario_maior["Nome"].unique())
display(salario_maior)

Regiao=df[df["Cidade"]=="Brasília"]
display(Regiao)

idade=df[df["Idade"]<30]
display(idade)

<StringArray>
['João', 'Maria', 'Pedro', 'Ana']
Length: 4, dtype: str

    Nome  Idade          Cidade  Salario  Salario_Anual
1   João     30       São Paulo     4200          50400
2  Maria     25  Rio de Janeiro     3800          45600
3  Pedro     40        Brasília     5000          60000
4    Ana     28         Goiânia     3100          37200

     Nome  Idade    Cidade  Salario  Salario_Anual
0  Amanda     21  Brasília     3000          30000
3   Pedro     40  Brasília     5000          60000

     Nome  Idade          Cidade  Salario  Salario_Anual
0  Amanda     21        Brasília     3000          30000
2   Maria     25  Rio de Janeiro     3800          45600
4     Ana     28         Goiânia     3100          37200

In [92]:
Regiao_Salario=df[(df["Cidade"]=="Brasília") & (df["Salario"]>3000)]
display(Regiao_Salario)

    Nome  Idade    Cidade  Salario  Salario_Anual
3  Pedro     40  Brasília     5000          60000

In [93]:
analise={
"Media dos salarios":df["Salario"].mean(),
"Maior valor":df["Salario"].max(),
"Menor valor":df["Salario"].min(),
"Média das Idades":df["Idade"].mean()
}
display(analise)

{'Media dos salarios': np.float64(3820.0),
 'Maior valor': np.int64(5000),
 'Menor valor': np.int64(3000),
 'Média das Idades': np.float64(28.8)}

In [95]:
dic_Salario={
"Maior Salário": df.sort_values(by=["Salario"],ascending=False),
"Menor Salário":df.sort_values(by=["Salario"],ascending=True),
"Salario Idade":df.sort_values(by=["Idade"], ascending=False)
}
display(dic_Salario)

{'Maior Salário':      Nome  Idade          Cidade  Salario  Salario_Anual
 3   Pedro     40        Brasília     5000          60000
 1    João     30       São Paulo     4200          50400
 2   Maria     25  Rio de Janeiro     3800          45600
 4     Ana     28         Goiânia     3100          37200
 0  Amanda     21        Brasília     3000          30000,
 'Menor Salário':      Nome  Idade          Cidade  Salario  Salario_Anual
 0  Amanda     21        Brasília     3000          30000
 4     Ana     28         Goiânia     3100          37200
 2   Maria     25  Rio de Janeiro     3800          45600
 1    João     30       São Paulo     4200          50400
 3   Pedro     40        Brasília     5000          60000,
 'Salario Idade':      Nome  Idade          Cidade  Salario  Salario_Anual
 3   Pedro     40        Brasília     5000          60000
 1    João     30       São Paulo     4200          50400
 4     Ana     28         Goiânia     3100          37200
 2   Maria     25  Rio de Janeiro     3800          45600
 0  Amanda     21        Brasília     3000          30000}

In [82]:
df["Salario_Anual"]=df["Salario"]*12
display(df)

     Nome  Idade          Cidade  Salario  Salario_Anual
0  Amanda     21        Brasília     2500          30000
1    João     30       São Paulo     4200          50400
2   Maria     25  Rio de Janeiro     3800          45600
3   Pedro     40        Brasília     5000          60000
4     Ana     28         Goiânia     3100          37200

In [ ]:
df.loc[0,"Salario"]=3000
display(df)

     Nome  Idade          Cidade  Salario  Salario_Anual
0  Amanda     21        Brasília     3000          30000
1    João     30       São Paulo     4200          50400
2   Maria     25  Rio de Janeiro     3800          45600
3   Pedro     40        Brasília     5000          60000
4     Ana     28         Goiânia     3100          37200

In [ ]:
display(df["Cidade"].value_counts())

Cidade
Brasília          2
São Paulo         1
Rio de Janeiro    1
Goiânia           1
Name: count, dtype: int64

In [ ]:
Salario_Max=df[df["Salario"]==df["Salario"].max()][["Nome","Salario"]]
display(Salario_Max)

    Nome  Salario
3  Pedro     5000

In [ ]:
Menores_30anos=df[df["Idade"]<30][["Nome","Cidade","Idade"]]
display(Menores_30anos)

     Nome          Cidade  Idade
0  Amanda        Brasília     21
2   Maria  Rio de Janeiro     25
4     Ana         Goiânia     28

In [ ]:
nova_linha={
"N_Nome":df["Nome"]=="Carlos",
"N_Idade":df["Idade"]=="35",
"N_Cidade":df["Cidade"]=="Salvador",
"Salario":df["Salario"]==4500
}

df["nova"]=nova_linha
display(df)

TypeError: Passing a dict as an indexer is not supported. Use a list instead.