In [1]:
#Crie uma tabela mostrando a média de Salario:
#nas linhas → Departamento
#nas colunas → Cidade
import pandas as pd
funcionarios=pd.read_csv("funcionarios.csv")
pedidos=pd.read_csv("pedidos.csv")
display(funcionarios,pedidos)

    ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479

    ID_Pedido  ID_Funcionario   Produto   Valor
0         101               1  Notebook  3500.0
1         102               2     Mouse   120.0
2         103               3   Teclado   180.0
3         104               1   Monitor   950.0
4         105               5   Headset   250.0
5         106               7  Notebook  4200.0
6         107               8     Mouse   130.0
7         108              10   Teclado   200.0
8         109              12   Monitor  1100.0
9         110              14    Webcam   300.0
10        111              16  Notebook  3800.0
11        112              17   Headset   280.0
12        113              18     Mouse   150.0
13        114              19   Monitor   980.0
14        115              20   Teclado   210.0

In [ ]:
#1. Crie uma tabela mostrando a média de Salario:
#nas linhas → Departamento
#nas colunas → Cidade
resultado=funcionarios.pivot_table(
index="Departamento",
columns="Cidade",
values="Salario",
aggfunc="mean",
)
display(resultado)

Cidade        Belo Horizonte  Brasília  Goiânia  Rio de Janeiro  São Paulo
Departamento
Financeiro            3803.5    5653.0   5311.0     4379.333333     4621.5
RH                    5557.0       NaN      NaN     2720.500000     4621.0
TI                    6149.0       NaN      NaN     5045.000000        NaN
Vendas                   NaN    4928.0      NaN             NaN     4522.0

In [5]:
#2. Total de salários por departamento e cidade
#Agora faça uma tabela mostrando o total de salários para cada combinação de:
#Departamento
#Cidade
#Você vai precisar mudar a função de agregação.
resultado=funcionarios.pivot_table(
    index="Departamento",
    columns="Cidade",
    values="Salario",
    aggfunc="sum"
)
display(resultado)

Cidade        Belo Horizonte  Brasília  Goiânia  Rio de Janeiro  São Paulo
Departamento
Financeiro            7607.0    5653.0  10622.0         13138.0     9243.0
RH                   11114.0       NaN      NaN          5441.0     4621.0
TI                    6149.0       NaN      NaN         10090.0        NaN
Vendas                   NaN    4928.0      NaN             NaN     4522.0

In [ ]:
#3. Crie uma tabela mostrando quantos funcionários existem em cada combinação de:
#Departamento
#Cidade
resultado=funcionarios.pivot_table(
    index="Departamento",
    columns="Cidade",
    values="Nome",
    aggfunc="count"
)
display(resultado)

Cidade        Belo Horizonte  Brasília  Goiânia  Rio de Janeiro  São Paulo
Departamento
Financeiro               2.0       1.0      2.0             3.0        2.0
RH                       2.0       NaN      NaN             2.0        1.0
TI                       1.0       NaN      NaN             2.0        NaN
Vendas                   NaN       1.0      NaN             NaN        1.0

In [3]:
#4. Maior salário
#Crie uma tabela mostrando o maior salário de cada combinação de:
#Departamento
#Cidade
resultado=funcionarios.pivot_table(
    index="Departamento",
    columns="Cidade",
    values="Salario",
    aggfunc="max"
)
display(resultado)

Cidade        Belo Horizonte  Brasília  Goiânia  Rio de Janeiro  São Paulo
Departamento
Financeiro            4847.0    5653.0   6182.0          6201.0     5979.0
RH                    5634.0       NaN      NaN          2756.0     4621.0
TI                    6149.0       NaN      NaN          5611.0        NaN
Vendas                   NaN    4928.0      NaN             NaN     4522.0

In [4]:
#5. Menor salário
#Faça a mesma coisa do exercício anterior, mas mostrando o menor salário.
resultado=funcionarios.pivot_table(
    index="Departamento",
    columns="Cidade",
    values="Salario",
    aggfunc="min"
)
display(resultado)

Cidade        Belo Horizonte  Brasília  Goiânia  Rio de Janeiro  São Paulo
Departamento
Financeiro            2760.0    5653.0   4440.0          2242.0     3264.0
RH                    5480.0       NaN      NaN          2685.0     4621.0
TI                    6149.0       NaN      NaN          4479.0        NaN
Vendas                   NaN    4928.0      NaN             NaN     4522.0

In [5]:
#6.
#Refaça o exercício 1, mas substitua os NaN por 0.
#Observe como o resultado muda.
resultado=funcionarios.pivot_table(
index="Departamento",
columns="Cidade",
values="Salario",
aggfunc="mean",
fill_value=0
)
display(resultado)

Cidade        Belo Horizonte  Brasília  Goiânia  Rio de Janeiro  São Paulo
Departamento
Financeiro            3803.5    5653.0   5311.0     4379.333333     4621.5
RH                    5557.0       0.0      0.0     2720.500000     4621.0
TI                    6149.0       0.0      0.0     5045.000000        0.0
Vendas                   0.0    4928.0      0.0        0.000000     4522.0

In [7]:
#7. Crie uma pivot_table() mostrando a média salarial por cidade e departamento, mas agora inverta:
#nas linhas → Cidade
#nas colunas → Departamento
resultado=funcionarios.pivot_table(
index="Cidade",
columns="Departamento",
values="Salario",
aggfunc="mean"
)
display(resultado)

Departamento     Financeiro      RH      TI  Vendas
Cidade
Belo Horizonte  3803.500000  5557.0  6149.0     NaN
Brasília        5653.000000     NaN     NaN  4928.0
Goiânia         5311.000000     NaN     NaN     NaN
Rio de Janeiro  4379.333333  2720.5  5045.0     NaN
São Paulo       4621.500000  4621.0     NaN  4522.0

In [11]:
#8.
#Crie um DataFrame pequeno contendo:
#Nome
#Departamento
#Cidade
#Salario
#com funcionários suficientes para que cada
#combinação de Departamento + Cidade apareça uma única vez.

dados = pd.DataFrame({
    "Nome": ["Ana", "João", "Maria", "Pedro"],
    "Departamento": ["TI", "TI", "RH", "RH"],
    "Cidade": ["Brasília", "Goiânia", "Brasília", "Goiânia"],
    "Salario": [5000, 4500, 3500, 4000]
})
display(dados)

resultado=dados.pivot(
    index="Departamento",
    columns="Cidade",
    values="Salario"
)
display(resultado)

    Nome Departamento    Cidade  Salario
0    Ana           TI  Brasília     5000
1   João           TI   Goiânia     4500
2  Maria           RH  Brasília     3500
3  Pedro           RH   Goiânia     4000

Cidade        Brasília  Goiânia
Departamento
RH                3500     4000
TI                5000     4500

In [12]:
#9.
#Usando o mesmo DataFrame do exercício anterior, faça o contrário:
#Cidade nas linhas
#Departamento nas colunas
#Salario como valores
resultado=dados.pivot(
    index="Cidade",
    columns="Departamento",
    values="Salario"
)
display(resultado)

Departamento    RH    TI
Cidade
Brasília      3500  5000
Goiânia       4000  4500

In [14]:
#10.Usando df_funcionarios, faça uma pivot_table() 
#que mostre duas informações ao mesmo tempo para cada departamento:
#média salarial
#maior salário
resultado=funcionarios.pivot_table(
index="Departamento",
columns="Cidade",
values="Salario",
aggfunc=["mean","max"]
)

display(resultado)

                       mean                                            \
Cidade       Belo Horizonte Brasília Goiânia Rio de Janeiro São Paulo
Departamento
Financeiro           3803.5   5653.0  5311.0    4379.333333    4621.5
RH                   5557.0      NaN     NaN    2720.500000    4621.0
TI                   6149.0      NaN     NaN    5045.000000       NaN
Vendas                  NaN   4928.0     NaN            NaN    4522.0

                        max
Cidade       Belo Horizonte Brasília Goiânia Rio de Janeiro São Paulo
Departamento
Financeiro           4847.0   5653.0  6182.0         6201.0    5979.0
RH                   5634.0      NaN     NaN         2756.0    4621.0
TI                   6149.0      NaN     NaN         5611.0       NaN
Vendas                  NaN   4928.0     NaN            NaN    4522.0

In [ ]:
#1.
#Crie uma tabela que mostre:
#Linhas: Cidade
#Colunas: Departamento
#Valores: Salario
#E faça com que cada célula mostre a média salarial.
#Depois:
#Substitua os NaN por 0

resultado=funcionarios.pivot_table(
    index="Cidade",
    columns="Departamento",
    values="Salario",
    aggfunc="mean",
    fill_value=0
)
display(resultado)