In [1]:
import pandas as pd
df=pd.read_csv("funcionarios.csv")
display(df)

    ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479

In [5]:
#1. Mostre todos os funcionários cujo Nome contém a letra "a"
#2. Mostre os funcionários cujo Nome contém "an".
#3. Crie uma coluna chamada Tem_A indicando True ou False para 
# cada funcionário, dependendo se o nome contém a letra "a".
a=df[df["Nome"].str.contains("a")]
an=df[df["Nome"].str.contains("an")]
df["Tem_A"]=df["Nome"].str.contains("a")
display(df)
display(a,an)

    ID      Nome  Idade          Cidade Departamento  Salario  Tem_A
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695   True
1    2     Julia     33  Belo Horizonte           TI     6149   True
2    3   Beatriz     37       São Paulo   Financeiro     3264   True
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201   True
4    5     Julia     36       São Paulo           RH     4621   True
5    6   Beatriz     25         Goiânia   Financeiro     4440   True
6    7    Carlos     42        Brasília       Vendas     4928   True
7    8     Julia     33  Rio de Janeiro           TI     5611   True
8    9  Fernanda     26  Belo Horizonte           RH     5480   True
9   10     Julia     38  Rio de Janeiro           RH     2685   True
10  11     Julia     38         Goiânia   Financeiro     6182   True
11  12    Rafael     35       São Paulo       Vendas     4522   True
12  13    Carlos     23  Belo Horizonte   Financeiro     2760   True
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242   True
14  15     Julia     44  Rio de Janeiro           RH     2756   True
15  16   Larissa     32       São Paulo   Financeiro     5979   True
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847   True
17  18    Rafael     33  Belo Horizonte           RH     5634   True
18  19    Carlos     22        Brasília   Financeiro     5653   True
19  20     Julia     23  Rio de Janeiro           TI     4479   True

    ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479

   ID      Nome  Idade          Cidade Departamento  Salario
3   4  Fernanda     36  Rio de Janeiro   Financeiro     6201
8   9  Fernanda     26  Belo Horizonte           RH     5480

In [6]:
# lower()
#4. Crie uma coluna chamada Nome_Minusculo contendo todos os nomes em letras minúsculas.
#5. Crie uma coluna Departamento_Minusculo com os departamentos em letras minúsculas.

df["Nome_Maiúsculo"]=df["Nome"].str.upper()
df["Nome_Minúsculo"]=df["Nome"].str.lower()
display(df)

,ID,Nome,Idade,Cidade,Departamento,Salario,Tem_A,Nome_Maiúsculo,Nome_Minúsculo
0,1,Rafael,21,Rio de Janeiro,Financeiro,4695,True,RAFAEL,rafael
1,2,Julia,33,Belo Horizonte,TI,6149,True,JULIA,julia
2,3,Beatriz,37,São Paulo,Financeiro,3264,True,BEATRIZ,beatriz
3,4,Fernanda,36,Rio de Janeiro,Financeiro,6201,True,FERNANDA,fernanda
4,5,Julia,36,São Paulo,RH,4621,True,JULIA,julia
5,6,Beatriz,25,Goiânia,Financeiro,4440,True,BEATRIZ,beatriz
6,7,Carlos,42,Brasília,Vendas,4928,True,CARLOS,carlos
7,8,Julia,33,Rio de Janeiro,TI,5611,True,JULIA,julia
8,9,Fernanda,26,Belo Horizonte,RH,5480,True,FERNANDA,fernanda
9,10,Julia,38,Rio de Janeiro,RH,2685,True,JULIA,julia
10,11,Julia,38,Goiânia,Financeiro,6182,True,JULIA,julia
11,12,Rafael,35,São Paulo,Vendas,4522,True,RAFAEL,rafael
12,13,Carlos,23,Belo Horizonte,Financeiro,2760,True,CARLOS,carlos
13,14,Beatriz,41,Rio de Janeiro,Financeiro,2242,True,BEATRIZ,beatriz
14,15,Julia,44,Rio de Janeiro,RH,2756,True,JULIA,julia
15,16,Larissa,32,São Paulo,Financeiro,5979,True,LARISSA,larissa
16,17,Gabriel,44,Belo Horizonte,Financeiro,4847,True,GABRIEL,gabriel
17,18,Rafael,33,Belo Horizonte,RH,5634,True,RAFAEL,rafael
18,19,Carlos,22,Brasília,Financeiro,5653,True,CARLOS,carlos
19,20,Julia,23,Rio de Janeiro,TI,4479,True,JULIA,julia

In [4]:
#Para esse exercício, primeiro crie uma pequena coluna com espaços extras.
#8. Crie:
#" Amanda "," João","Maria "," Pedro "
#Depois remova os espaços do começo e do final usando strip().
df_nomes = pd.DataFrame({
    "Nomes": [" Amanda ", " João", "Maria ", " Pedro "]
})
df_nomes["Nomes"]=df_nomes["Nomes"].str.strip()
display(df_nomes)

    Nomes
0  Amanda
1    João
2   Maria
3   Pedro

In [4]:
#replace()
#9. Na coluna Departamento, troque:
#"TI" → "Tecnologia"
#10. Troque:
#"RH" → "Recursos Humanos"
df["Departamento_Novo"]=df["Departamento"].str.replace("TI","Tecnologia")
df["Departamento_Novo"]=df["Departamento_Novo"].str.replace("RH","Recursos Humanos")
display(df)

,ID,Nome,Idade,Cidade,Departamento,Salario,Departamento_Novo
0,1,Rafael,21,Rio de Janeiro,Financeiro,4695,Financeiro
1,2,Julia,33,Belo Horizonte,TI,6149,Tecnologia
2,3,Beatriz,37,São Paulo,Financeiro,3264,Financeiro
3,4,Fernanda,36,Rio de Janeiro,Financeiro,6201,Financeiro
4,5,Julia,36,São Paulo,RH,4621,Recursos Humanos
5,6,Beatriz,25,Goiânia,Financeiro,4440,Financeiro
6,7,Carlos,42,Brasília,Vendas,4928,Vendas
7,8,Julia,33,Rio de Janeiro,TI,5611,Tecnologia
8,9,Fernanda,26,Belo Horizonte,RH,5480,Recursos Humanos
9,10,Julia,38,Rio de Janeiro,RH,2685,Recursos Humanos
10,11,Julia,38,Goiânia,Financeiro,6182,Financeiro
11,12,Rafael,35,São Paulo,Vendas,4522,Vendas
12,13,Carlos,23,Belo Horizonte,Financeiro,2760,Financeiro
13,14,Beatriz,41,Rio de Janeiro,Financeiro,2242,Financeiro
14,15,Julia,44,Rio de Janeiro,RH,2756,Recursos Humanos
15,16,Larissa,32,São Paulo,Financeiro,5979,Financeiro
16,17,Gabriel,44,Belo Horizonte,Financeiro,4847,Financeiro
17,18,Rafael,33,Belo Horizonte,RH,5634,Recursos Humanos
18,19,Carlos,22,Brasília,Financeiro,5653,Financeiro
19,20,Julia,23,Rio de Janeiro,TI,4479,Tecnologia

In [6]:
#split()
#12. Pegue a coluna Nome e transforme cada nome em uma lista de palavras.
nomes=pd.DataFrame({
    "Nome":["Amanda Meireles","Stuart Raw","Lila Olivia"]
})

nomes["Nome"]=nomes["Nome"].str.split(" ")
display(nomes)

                 Nome
0  [Amanda, Meireles]
1       [Stuart, Raw]
2      [Lila, Olivia]