In [2]:
import pandas as pd
import numpy as np

df=pd.read_csv("funcionarios.csv")
display(df)

    ID      Nome  Idade          Cidade Departamento  Salario
0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
1    2     Julia     33  Belo Horizonte           TI     6149
2    3   Beatriz     37       São Paulo   Financeiro     3264
3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
4    5     Julia     36       São Paulo           RH     4621
5    6   Beatriz     25         Goiânia   Financeiro     4440
6    7    Carlos     42        Brasília       Vendas     4928
7    8     Julia     33  Rio de Janeiro           TI     5611
8    9  Fernanda     26  Belo Horizonte           RH     5480
9   10     Julia     38  Rio de Janeiro           RH     2685
10  11     Julia     38         Goiânia   Financeiro     6182
11  12    Rafael     35       São Paulo       Vendas     4522
12  13    Carlos     23  Belo Horizonte   Financeiro     2760
13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
14  15     Julia     44  Rio de Janeiro           RH     2756
15  16   Larissa     32       São Paulo   Financeiro     5979
16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
17  18    Rafael     33  Belo Horizonte           RH     5634
18  19    Carlos     22        Brasília   Financeiro     5653
19  20     Julia     23  Rio de Janeiro           TI     4479

In [13]:
#Exercício 1 — Explorando os dados
#Leia o arquivo CSV e responda:
#Quantas linhas existem?
#Quantas colunas existem?
#Quais são os tipos de dados?
#Existem valores nulos?

display(df.shape[0])
display(df.shape[1])

display(df.info())
display(df.isnull().sum())

20

6

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            20 non-null     int64
 1   Nome          20 non-null     str
 2   Idade         20 non-null     int64
 3   Cidade        20 non-null     str
 4   Departamento  20 non-null     str
 5   Salario       20 non-null     int64
dtypes: int64(3), str(3)
memory usage: 1.1 KB

None

ID              0
Nome            0
Idade           0
Cidade          0
Departamento    0
Salario         0
dtype: int64

In [2]:
#Exercício 2 — Valores nulos
# Mostre apenas as linhas que possuem pelo menos um valor nulo.

df_analise=df[df.isnull().any(axis=1)]
display(df_analise)

Empty DataFrame
Columns: [ID, Nome, Idade, Cidade, Departamento, Salario]
Index: []

In [ ]:
#Exercício 3 — Valores preenchidos
#Mostre apenas as linhas que não possuem nenhum valor nulo.
#Objetivo: notnull().
df_analise=df[df.notnull().all(axis=1)]
display(df_analise)

In [ ]:
#Exercício 4 — Contando nulos
# Descubra:Quantos valores nulos existem em cada coluna.
df_analise=df.isnull().sum()
display(df_analise)

In [ ]:
#Exercício 5 — Preenchendo valores
# Preencha:
# Salários nulos com 0.
# Cidade nula com "Não informado".
# Objetivo: fillna().

df["Salario"]=df["Salario"].fillna(0)
df["Cidade"]=df["Cidade"].fillna("Não informado")
display(df)

In [ ]:
#Exercício 6 — Removendo linhas
#Remova todas as linhas que possuem algum valor nulo.
#Objetivo: dropna().
display(df.dropna())

In [ ]:
#Exercício 7 — Removendo apenas quando faltar salário
#Remova somente as linhas onde o Salario é nulo.
analise_salario=df.dropna(subset=["Salario"])
display(analise_salario)

In [7]:
#Exercício 8 — Valores duplicados 
# Descubra: Existem funcionários duplicados?
df_analise=df["Nome"].duplicated().any()
display(df_analise)

np.True_

In [ ]:
#Exercício 9 — Remover duplicados
#Remova todos os registros duplicados.
df=df.drop_duplicates()
display(df)

In [ ]:
#Exercício 10 — Substituindo valores
# Troque:
# "TI" por "Tecnologia".
df["Departamento"]=df["Departamento"].replace({
"TI":"Tecnologia"
})
display(df)

In [ ]:
#Exercício 11 — Outra substituição
# Troque:
# "RH" por "Recursos Humanos".
df["Departamento"]=df["Departamento"].replace({
    "RH":"Recursos Humanos"
})
display(df)

In [ ]:
#Exercício 12 — Alterando tipo
# Transforme a coluna Idade para inteiro
#Objetivo: astype().
df["Idade"]=df["Idade"].astype(int)
display(df.info())

In [21]:
#Exercício 13 — Outra conversão
#Transforme a coluna Salario para float.
df["Salario"]=df["Salario"].astype(float)
display(df.dtypes)

ID                int64
Nome                str
Idade             int64
Cidade              str
Departamento        str
Salario         float64
dtype: object

In [ ]:
#Exercício 14 — Tudo junto
# Faça um tratamento completo:
# Remova duplicados.
# Preencha cidades vazias.
# Remova salários nulos.
# Troque "TI" por "Tecnologia".
# Converta salário para float.
df_analise=df.drop_duplicates()
df_analise["Cidade"]=df_analise["Cidade"].fillna("Nao encontrado")
df_analise=df_analise.dropna(subset=["Salario"])
df_analise["Departamento"]=df_analise["Departamento"].replace({
    "Tecnologia":"TI"
})
df_analise["Salario"]=df_analise["Salario"].astype(float)
display(df_analise)

In [ ]:
#Desafio 1
# Mostre apenas os funcionários que possuem cidade preenchida.
analise_funcionario=df[df["Cidade"].notnull()]
display(analise_funcionario)

In [10]:
#Desafio 2
#Depois do tratamento:
# Mostre:
# Média salarial por departamento.
media_salarial=df.groupby("Departamento")["Salario"].mean()
display(media_salarial)

Departamento
Financeiro    4626.3
RH            4235.2
TI            5413.0
Vendas        4725.0
Name: Salario, dtype: float64

In [15]:
#Desafio 3
# Crie um relatório contendo:
# Quantidade de funcionários
# Quantos valores nulos existiam
# Quantos registros duplicados existiam
# Quantas linhas foram removidas
# Quantas linhas ficaram no DataFrame final
analise_funcionario=df["Nome"].count()
nulos=df.isnull().sum().sum()
duplicados=df.drop_duplicates()
cont_linha=len(df) - len(duplicados)
linhas_finais=len(duplicados)

relatorio={
 "Quantidade de funcionários:":analise_funcionario,
 "Quantos valores nulos existiam:":nulos,
 "Quantos registros duplicados existiam:":duplicados,
 "Quantas linhas foram removidas:":cont_linha,
 "Quantas linhas ficaram no DataFrame final":cont_linha
}
display(relatorio)

{'Quantidade de funcionários:': np.int64(20),
 'Quantos valores nulos existiam:': np.int64(0),
 'Quantos registros duplicados existiam:':     ID      Nome  Idade          Cidade Departamento  Salario
 0    1    Rafael     21  Rio de Janeiro   Financeiro     4695
 1    2     Julia     33  Belo Horizonte           TI     6149
 2    3   Beatriz     37       São Paulo   Financeiro     3264
 3    4  Fernanda     36  Rio de Janeiro   Financeiro     6201
 4    5     Julia     36       São Paulo           RH     4621
 5    6   Beatriz     25         Goiânia   Financeiro     4440
 6    7    Carlos     42        Brasília       Vendas     4928
 7    8     Julia     33  Rio de Janeiro           TI     5611
 8    9  Fernanda     26  Belo Horizonte           RH     5480
 9   10     Julia     38  Rio de Janeiro           RH     2685
 10  11     Julia     38         Goiânia   Financeiro     6182
 11  12    Rafael     35       São Paulo       Vendas     4522
 12  13    Carlos     23  Belo Horizonte   Financeiro     2760
 13  14   Beatriz     41  Rio de Janeiro   Financeiro     2242
 14  15     Julia     44  Rio de Janeiro           RH     2756
 15  16   Larissa     32       São Paulo   Financeiro     5979
 16  17   Gabriel     44  Belo Horizonte   Financeiro     4847
 17  18    Rafael     33  Belo Horizonte           RH     5634
 18  19    Carlos     22        Brasília   Financeiro     5653
 19  20     Julia     23  Rio de Janeiro           TI     4479,
 'Quantas linhas foram removidas:': 0,
 'Quantas linhas ficaram no DataFrame final': 0}